# Generated by Django 5.0.3 on 2024-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=100)),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('num_chamado', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Atendido', 'Atendido')], default='Pendente', max_length=100)),
                ('data_solicitacao', models.DateField()),
            ],
        ),
    ]
